from selenium.webdriver.common.by import By

name_input = [By.XPATH, '//input[@placeholder="* Имя"]']
sec_name_input = [By.XPATH, '//input[@placeholder="* Фамилия"]']
address_input = [By.XPATH, '//input[@placeholder="* Адрес: куда привезти заказ"]']
metro_select = [By.XPATH, 'div[@class="select-search__value"]']
metro_input = [By.XPATH, '//input[@placeholder="* Станция метро"]']
phone_input = [By.XPATH, '//input[@placeholder="* Телефон: на него позвонит курьер"]']
next_button = [By.XPATH, '//button[text()="Далее"]']
date_input = [By.XPATH, '//input[@placeholder="* Когда привезти самокат"]']
rental_period_input = [By.XPATH, '//div[text()="* Срок аренды"]']
day_period = [By.XPATH, '//div[text()="сутки"]']
two_days_period = [By.XPATH, '//div[text()="двое суток"]']
color_label_black = [By.XPATH, '//label[text()="чёрный жемчуг"]']
color_label_gray = [By.XPATH, '//label[text()="серая безысходность"]']
comment_input = [By.XPATH, '//input[@placeholder="Комментарий для курьера"]']
order_page_order_button = [By.XPATH, '//div[@class="Order_Buttons__1xGrp"]/button[2]']
confirm_button = [By.XPATH, '//button[text()="Да"]']
confirm_text = [By.XPATH, '//div[@class="Order_ModalHeader__3FDaJ"]']